### PR TITLE
Fix memory leaks

### LINKED ISSUE #2217: Memory leak after closing new chat window
To reproduce issue:
- Open your favourite task manager (to watch memory growth)
- Launch qtox
- Open new chat window from any contact
- Close it
- Repeat 2 last steps until you notice that some memory still isn't freed after new chat window closed

### PR DESCRIPTION
**Pull request by dmshynk**
Some more progress on memory leaks, one fixed use of an uninitialized variable. No longer able to reproduce #2308 with these changes. Still unable to fix #2217, any insights are welcome.

### CODE REVIEW

File: src/video/cameradevice.cpp [hunk 1]
```diff
@@ -225,7 +225,6 @@ QVector<QPair<QString, QString>> CameraDevice::getRawDeviceListGeneric()
     if (av_opt_set_dict2(s, &tmp, AV_OPT_SEARCH_CHILDREN) < 0)
     {
         av_dict_free(&tmp);
-        avformat_free_context(s);
```
Comment (tux3) [inline src/video/cameradevice.cpp:228]: You're introducing a new leak here if we return early at line 233
Instead, if av_opt_set_dict2 fails we should keep the avformat_free_context(s); at line 228 and return early here, and if it doesn't fail we should add:

```
av_dict_free(&tmp);
avformat_free_context(s);
```

right after the avdevice_list_devices (no need to wait until the end of the function).
That part of the code is pretty much a copy of `list_devices_for_context`, which isn't in the public API for some reason.

**Comment by dmshynk** [comment]
@tux3, done and done. Thanks for pointing this out, guess I should really spend more time reading the docs.

**Comment by dmshynk** [comment]
I don't even know what to say for myself:clap: It was literally the second thing you mentioned in the original message. Fixed

File: src/platform/statusnotifier/statusnotifier.c [hunk 2]
```diff
@@ -1608,7 +1608,7 @@ get_prop (GDBusConnection        *conn,
     else if (!g_strcmp0 (property, "ToolTip"))
     {
         GVariant *variant;
-        GVariantBuilder *builder;
+        GVariant *pixmap;
```
Comment (antis81) [inline src/platform/statusnotifier/statusnotifier.c]: Yeah, I've noticed the warning here… :+1:

File: src/widget/systemtrayicon.cpp [hunk 3]
```diff
@@ -72,11 +72,15 @@ SystemTrayIcon::SystemTrayIcon()
         };
         QImage* image = new QImage(":/img/icon.png");
```
Comment (antis81) [inline src/widget/systemtrayicon.cpp]: ~~Same procedure as last year ;) - Use stacked variable simplifies life.~~

Why are we're misusing QImage here to create the GdkPixbuf object? Isn't it able to load the image data from file directly instead?

Other than that, IMO the `StatusNotifier` type should change to either one of `QIcon`, `QImage` or `QPixmap`.

File: src/widget/systemtrayicon.cpp [hunk 4]
```diff
@@ -107,16 +111,19 @@ SystemTrayIcon::SystemTrayIcon()
...
-        QImage image(":/img/icon.png");
-        if (image.format() != QImage::Format_RGBA8888_Premultiplied)
-        image = image.convertToFormat(QImage::Format_RGBA8888_Premultiplied);
-        GdkPixbuf* pixbuf = gdk_pixbuf_new_from_data(image.bits(), GDK_COLORSPACE_RGB, image.hasAlphaChannel(),
-                                 8, image.width(), image.height(),
-                                 image.bytesPerLine(), callbackFreeImage, &image);
+        QImage* image = new QImage(":/img/icon.png");
+        if (image->format() != QImage::Format_RGBA8888_Premultiplied)
+            *image = image->convertToFormat(QImage::Format_RGBA8888_Premultiplied);
+        GdkPixbuf* pixbuf = gdk_pixbuf_new_from_data(image->bits(), GDK_COLORSPACE_RGB, image->hasAlphaChannel(),
```
Comment (antis81) [inline src/widget/systemtrayicon.cpp]: Anything against using `QImage` (or QPixmap?) all the way?

File: src/widget/systemtrayicon.cpp [hunk 5]
```diff
@@ -233,13 +244,17 @@ void SystemTrayIcon::setContextMenu(QMenu* menu)
                 };
                 QImage* image = new QImage(a->icon().pixmap(64, 64).toImage());
                 if (image->format() != QImage::Format_RGBA8888_Premultiplied)
-                *image = image->convertToFormat(QImage::Format_RGBA8888_Premultiplied);
+                    *image = image->convertToFormat(QImage::Format_RGBA8888_Premultiplied);
                 GdkPixbuf* pixbuf = gdk_pixbuf_new_from_data(image->bits(), GDK_COLORSPACE_RGB, image->hasAlphaChannel(),
```
Comment (antis81) [inline src/widget/systemtrayicon.cpp]: **important** Will need to `memcpy` the `image->bits()` here, as these are shared implicitly and become invalid, when QImage is deleted.

After doing so, QImage can be created on stack again.

File: src/widget/systemtrayicon.cpp (hunk 4 above)
Comment (agilob) [inline src/widget/systemtrayicon.cpp]: afair QPixmap had problem with transparent icons in a version of Qt.

**Comment by agilob** [comment]
@dmshynk could you fix the issue pointed by @antis81  so I can merge it?

File: src/widget/systemtrayicon.cpp (hunk 4 above)
Comment (antis81) [inline src/widget/systemtrayicon.cpp]: Hm… this cannot be correct in this case. We use QImage here to load and initialize image data, but then transport the data to a gtk object. To me this looks like a pretty dirty hack -> and it crashes, because data isn't copied, but implicitly shared here (see docs for QImage::bits()). This requires a `memcpy(QImage::bits())`. Otherwise image data become invalid for `GdkPixbuf` when QImage is deleted.

Comment (agilob) [inline src/widget/systemtrayicon.cpp]: That was the reason for using qimage,  don't know anything about gdkpixbuf.

File: src/widget/systemtrayicon.cpp (hunk 5 above)
Comment (dmshynk) [inline src/widget/systemtrayicon.cpp]: But the ```image``` won't get deleted until after ```pixbuf```'s reference count has dropped to zero, as per [docs](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Image-Data-in-Memory.html#gdk-pixbuf-new-from-data). Note that the deletion only happens in the callback passed to ```gdk_pixbuf_new_from_data()```.

File: src/widget/systemtrayicon.cpp (hunk 4 above)
Comment (dmshynk) [inline src/widget/systemtrayicon.cpp]: Plus, using ```QPixmap``` is impractical in this case, as it doesn't provide an interface to extract raw data, like ```QImage::bits()```. Now, notice how the ```else```  block uses a ```QSystemTrayIcon```, the Qt-native solution, which doesn't really work — see [this bug](https://bugreports.qt.io/browse/QTBUG-31762), never fully resolved, AFAIK. However, for Plasma 5,we could go with a native solution starting from Qt5.4 (see [here](http://blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/)). I'll look into it.

File: src/widget/systemtrayicon.cpp (hunk 5 above)
Comment (antis81) [inline src/widget/systemtrayicon.cpp]: Phew, this is is total brain f*_k. You're right, the callback reinterpret_casts gpointer to QImage_ and free's it. But… we don't actually need the callback here don't you think? As this code is addressed to GTK+ backend, we should rather use completely their classes and replace the `QImage` code here IMO.

File: src/widget/systemtrayicon.cpp [hunk 6]
```diff
@@ -366,11 +381,15 @@ void SystemTrayIcon::setIcon(QIcon &icon)
         };
         QImage* image = new QImage(icon.pixmap(64, 64).toImage());
         if (image->format() != QImage::Format_RGBA8888_Premultiplied)
-        *image = image->convertToFormat(QImage::Format_RGBA8888_Premultiplied);
+            *image = image->convertToFormat(QImage::Format_RGBA8888_Premultiplied);
         GdkPixbuf* pixbuf = gdk_pixbuf_new_from_data(image->bits(), GDK_COLORSPACE_RGB, image->hasAlphaChannel(),
                                  8, image->width(), image->height(),
                                  image->bytesPerLine(), callbackFreeImage, image);
+        if(!pixbuf) // If pixbuf initialization fails, it won't trigger the callback.
```
Comment (antis81) [inline src/widget/systemtrayicon.cpp]: This looks bullshit to me. If pixbuf initialization fails, the callback should be still called. Are you sure about this?

Comment (dmshynk) [inline src/widget/systemtrayicon.cpp]: It should, but valgrind analysis suggests otherwise. I suppose the *correct* approach would be to switch to gtk-specific ```GBytes``` in place of ```QImage```, as you noted above, then we could use [```gdk_pixbuf_new_from_bytes```](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-Image-Data-in-Memory.html#gdk-pixbuf-new-from-bytes) and forgo the hassle of freeing in a callback and that all. I'll look into that as well.

Comment (antis81) [inline src/widget/systemtrayicon.cpp]: That sounds better. Thanks a lot. :+1:

**Comment by dmshynk** [comment]
Done what could be done, now working on getting rid of ```SystemTrayIcon``` and GTK+ bindings completely, replacing them with a plain ```QSystemTrayIcon```. Seems to work on at least Plasma 5.4 and Unity 7.3, more testing is needed. That will be a separate pull request, though.

**Comment by zetok** [comment]
@dmshynk sounds great `:)`

Will removal GTK+ stuff be based on #2132?

**Comment by dmshynk** [comment]
@zetok, definitely, as soon as it gets merged. By the way, Travis is apparently using an older version of ```libgdk-pixbuf``` (```gdk_pixbuf_new_from_bytes()``` was introduced in v.2.32, which Ubuntu doesn't get until 15.10). What do?

**Comment by agilob** [comment]
Ubuntu is like Windows of Linuxes.

**Comment by antis81** [comment]
@dmshynk A big thank you. Can you fix build please before merge (missing include?):

```
src/widget/systemtrayicon.cpp: In member function ‘void SystemTrayIcon::setContextMenu(QMenu*)’:

src/widget/systemtrayicon.cpp:176:96: error: ‘gdk_pixbuf_new_from_bytes’ was not declared in this scope

                                          8, image.width(), image.height(), image.bytesPerLine());

                                                                                                ^

src/widget/systemtrayicon.cpp:220:95: error: ‘gdk_pixbuf_new_from_bytes’ was not declared in this scope

                                         8, image.width(), image.height(), image.bytesPerLine());

                                                                                               ^

src/widget/systemtrayicon.cpp: In member function ‘void SystemTrayIcon::setIcon(QIcon&)’:

src/widget/systemtrayicon.cpp:352:87: error: ‘gdk_pixbuf_new_from_bytes’ was not declared in this scope

                                 8, image.width(), image.height(), image.bytesPerLine());

                                                                                       ^

src/widget/systemtrayicon.cpp:368:87: error: ‘gdk_pixbuf_new_from_bytes’ was not declared in this scope

                                 8, image.width(), image.height(), image.bytesPerLine());

                                                                                       ^
```

**Comment by agilob** [comment]
What include is missing?

**Comment by dmshynk** [comment]
@agilob, nothing is missing, all compiles just fine on my machine. The issue is with Travis CI's environment. Since it's Ubuntu 12.04 LTS ([prooflink](http://docs.travis-ci.com/user/ci-environment/)), ```libgtk-pixbuf``` is at v.2.26, which means that ```gdk_pixbuf_new_from_bytes``` is simply not there to include, as it is not introduced until v.2.32. There is no good way around it, aside from [pinning](https://help.ubuntu.com/community/PinningHowto), which is totally not worth it since we are planning on getting rid of GTK+ deps anyway. Meanwhile, I guess we'll have to resort to using a crude ```guchar*``` and the godawful deletion in callback to make it build.

**Comment by agilob** [comment]
I will merge it today unless there are objections.

**Comment by tux3** [comment]
LGTM

**Comment by tux3** [comment]
Actually let's merge that right now, and then #2132

**Comment by agilob** [comment]
Ok, so I will fix #2132 to remove unused code, it contains a fix that was already merged. It will be fixed in different PR. I'll to by best to do to it today!

**Comment by tux3** [comment]
Don't worry, I'm rebasing and fixing up #2132 right now, then I can panic about new AV not being ready...

**Comment by agilob** [comment]
ok, thanks
